# -*- coding: utf-8 -*-
"""Task(Python.while).ipynb adlı not defterinin kopyası

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6W4j6gj6OGo5GB8t8gk0Btqmx3AUDEp

1) Get the keys from the dictionaries named *sample_dic* as a list
```
sample_dict = {
    'Physics': 82,
    'Math': 65,
    'history': 75
}
```

2) Get sum of all the values in a dict

```
#Input:
sample_dict = {
    'Physics': 82,
    'Math': 65,
    'history': 75,
    'chemistry': 89,
    'GK': 50
    
}

#Expected Output: 361

```

3)Get the key of a minimum value from the following dictionary

```
#Input:
sample_dict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}

#Expected Output: Math

```

4) Delete a list of keys from a dictionary
```
#Inputs:
sample_dict = {
    "name": "Khalid",
    "age": 23,
    "salary": 1000,
    "city": "Baku"
}

# Keys to remove
keys = ["name", "salary"]

# Expected Output: {'city': 'Baku', 'age': 23}
```

5) Create a dictionary by extracting the keys from a given dictionary

```
# Inputs:
sample_dict = {
    "name": "Khalid",
    "age": 23,
    "salary": 1000,
    "city": "Baku"}

# Keys to extract
keys = ["name", "salary"]

# Expected Output: {'name': 'Khalid', 'salary': 1000}
```

6) Take 10 integers from keyboard using loop and print their average value
on the screen.

7) Print multiplication table of 24 using loop.

8) Factorial of any number n is represented by n! and is equal to 1*2*3*....*(n-1)*n.

Write a program to calculate factorial of a number.

```
4! = 1*2*3*4 = 24
3! = 3*2*1 = 6
2! = 2*1 = 2

Also,
1! = 1
0! = 1
```

9) Write a program that calculates the sum of the digits of a given number. Ask the user to input a number

10) Write a Python program that takes a string input from the user and counts the number of characters in the string.
"""

# Sual 1
sample_dic=[]
sample_dict = {
    'Physics': 82,
    'Math': 65,
    'history': 75
}
sample_dic.append(sample_dict.keys())
print(sample_dic)

# Sual 2
sample_dict = {
    'Physics': 82,
    'Math': 65,
    'history': 75,
    'chemistry': 89,
    'GK': 50

}
print(sum(sample_dict.values()))

# Sual 3
sample_dict = {
  'Physics': 82,
  'Math': 65,
  'history': 75
}
a=min(sample_dict.items())
print(a[0])

# Sual 4
sample_dict = {
    "name": "Khalid",
    "age": 23,
    "salary": 1000,
    "city": "Baku"
}
del sample_dict["name"],sample_dict["salary"]
print(sample_dict)

# Sual 5
sample_dict = {
    "name": "Khalid",
    "age": 23,
    "salary": 1000,
    "city": "Baku"}
keys = ["name", "salary"]
for key in sample_dict.keys():
  if key in keys:
    print({key: sample_dict[key]})

# Sual 6
n=0
sum=0
while n<10:
  num=int(input("Enter num"))
  n+=1
  sum+=num
print(sum/n)

# Sual 7
num=24
n=0
while n<10:
  n+=1
  result=num*n
  print(f"{num} x {n}= {result}")

# Sual 8
num=int(input(" Enter num: "))
hasil=1
while num>1:
  hasil*=num
  num-=1
print(hasil)

# Sual 9
sum=0
number=input("Please enter number :)   ")
for i in number:
  sum+=int(i)
print(sum)

# Sual 10
sum=0
string=input("Please enter string ")
for char in string:
  sum+=1
print(sum)